### ISSUE TITLE
YandexWeather is showing words instead of emojis

### ISSUE THREAD

**Issue by valeriu33** [Toxblh/MTMR#238] opened 2019-11-12 20:25 UTC
I'd like to use YandexWeather widget, as i find it more accurate for my region (i know that its WIP)
All i need is a little improvement to allow widget show emojis instead of text (like in other weather widget), and i found this dictionary here:
` (YandexWeatherBarItem.swift)   private let iconsSource = ["Ясно": "☀️", "Малооблачно": "🌤", "Облачно с прояснениями": "⛅️", "Пасмурно": "☁️", "Небольшой дождь": "🌦", "Дождь": "🌧", "Ливень": "⛈", "Гроза": "🌩", "Дождь со снегом": "☔️", "Небольшой снег": "❄️", "Снег": "🌨", "Туман": "🌫"]`
As I see, you expect the response from API to be in russian
Please add english words

Thanks

**Comment by bobrosoft** [comment] 2019-11-20 13:41
Hi @valeriu33 ,
From which country are you? Initially I thought to add English words as well but then found that YandexWeather returns weather response only in Russian language and that piece of source code you dropped above used to map words response to proper Emoji icon. I tried to test with American/Europe VPN enabled before and seen no difference in response, always Russian language was used there, no auto-detection, so I had no information to add proper matches. Maybe things changed now, I can retry later.

**Comment by bobrosoft** [comment] 2019-11-20 13:54
@valeriu33 just checked again through US VPN -- no difference, all in Russian language, so should work. What words do you see particularly? I can't see Russian language on https://yandex.ru/weather/ changed to something else when using US network and all English locale.

**Comment by valeriu33** [comment] 2019-12-06 07:59
Hi @bobrosoft 
I'm from Moldova. Sorry for long time no answer. Firstly, i find this app really useful, thanks
I'm using MTMR 0.25
**My settings:**  

**YandexWeather:**
```
{   "type": "yandexWeather",
    "refreshInterval": 600,
    "icon_type": "images" },
```
on Touchbar is says _Clear_
Same with `"icon_type": "text"`

**While normal weather:**
```
{     "type": "weather",
      "refreshInterval": 600,
      "icon_type": "images",
       ...
}
```
on Touch Bar says ☀️,
when "icon_type": "text": ☼ 

I just want them widgets to have the same behavior

Thank you!

**Comment by bobrosoft** [comment] 2019-12-06 08:39
Ok, so, Moldova.. I will try. Strange that I can't reproduce it normally with US VPN. Need to try harder. Btw, you can make me a good favor if you open https://yandex.ru/weather/kishinev  and can find all matching words which corresponds to all these icons:
["Ясно": "☀️", "Малооблачно": "🌤", "Облачно с прояснениями": "⛅️", "Пасмурно": "☁️", "Небольшой дождь": "🌦", "Дождь": "🌧", "Ливень": "⛈", "Гроза": "🌩", "Дождь со снегом": "☔️", "Небольшой снег": "❄️", "Снег": "🌨", "Туман": "🌫"]

if it shows correctly in english for you, you can click on other cities and countries with another weather to find all words variation used there. Then I can extend that array I have there and it will work for you as well in next release.

**Comment by valeriu33** [comment] 2019-12-06 08:42
Ok, but it may take a while

**Comment by valeriu33** [comment] 2019-12-28 22:36
[
        "Ясно": "Clear",
        "Малооблачно": "Mostly clear",
        "Облачно с прояснениями": "Partly cloudy", 
        "Пасмурно": "Overcast", 
        "Небольшой дождь": "Light rain", 
        "Дождь": "Rain", 
        "Ливень": "shower", 
        "Гроза": "Storm", 
        "Дождь со снегом": "Sleet",
        "Небольшой снег": "Light snow", 
        "Снег": "Snow", 
        "Туман": "Fog"
     ]

**Comment by bobrosoft** [comment] 2019-12-30 07:47
@valeriu33 good, updated. You can try next build: https://www.dropbox.com/s/ddsk2hkt4alrphv/MTMR%202019-12-30%2011-45-50.zip?dl=0
And Happy New Year :)

**Comment by maandagdev** [comment] 2020-01-08 15:25
The update has been merged, I think this issue can be closed?

**Closed** 2020-01-09 04:12 UTC
